name: Deploy Static Website with Terraform

on:
  push:
    branches: 
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1  # or your region

      - name: Terraform Init
        run: terraform init
        working-directory: Staticwebsite_with_terraform

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: Staticwebsite_with_terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: Staticwebsite_with_terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: Staticwebsite_with_terraform

